### ISSUE TITLE
components(): objects with same label across mat-borders

### ISSUE THREAD

**Issue by EhrmannS** [jonclayden/mmand#2]
Great package! I am about to use it as dependency for a package I am working on myself atm. However, I think I found a bug.
Consider the following code:

      mat <- raster::as.matrix(spObj)
      kernel <- shapeKernel(c(3, 3), type="diamond")
      mat_cc <- mmand::components(mat, kernel)

It seems (at least on my machine) that connected components at the bottom and at the top share the same label. I think this is not intentional, is it? Here is [spObj](https://github.com/EhrmannS/r-snippets/blob/master/data/spObj.RData)

**Comment by jonclayden** [comment]
Many thanks for the report. This should be fixed in the master branch by commit 1c8b364. I've tried it on your test data and it now seems to behave correctly, but if you could confirm that it works for you that would be very helpful. All the best!

**Comment by EhrmannS** [comment]
I can confirm that it works. That was quick, thanks!

**Comment by jonclayden** [comment]
Great! I'll get a v1.5.1 release cut and sent to CRAN today.
