### ISSUE TITLE
boxKernel() in rescale() produces "checkered" plot

### ISSUE THREAD

**Issue by EhrmannS** [jonclayden/mmand#3]
Hi there, I think I found another bug. Not 100% sure though, since am not fully able to deduce what the `boxKernel()` is actually supposed to do in `rescale()`. Anyway, when I do

      mat <- raster::as.matrix(spObj)
      mat_resc <- mmand::rescale(mat, 2, kernel)
      spObj_resc <- raster::raster(mat_resc)
      raster::extent(spObj_resc) <- raster::extent(spObj)
      sp::proj4string(spObj_resc) <- sp::proj4string(spObj)

spObj obviously is a binary raster with certain dimensions (97, 201, 19497  (nrow, ncol, ncell)) and spObj_resc with double the nrows/ncols and four times the ncells (194, 402, 77988  (nrow, ncol, ncell)), as expected. What is not expected though, is that when plotting spObj_resc (`raster::plot()`, but its the same with `display()` on `mat_resc`), I get a [funny looking raster](https://github.com/EhrmannS/r-snippets/blob/master/data/Rplot.svg), where only the lower right cell (of four cells) is "filled" with a value, while the other three (presumably new created cells) have the value 0. This is also irrespective of binary or continuous raster.

Moreover, if I chose a values for `factor` of for instance 0.5, something similar arises, however on the scale of the whole plot, only the upper left fourth of the downscaled plot is shown.

These issues don't seem to arise at least with the mnKernel(), didn't test the others though.
[spObj](https://github.com/EhrmannS/r-snippets/blob/master/data/spObj.RData) is still the same.

**Comment by jonclayden** [comment]
Thanks for the report, Steffen. I think this is fixed on the master branch now, but I'd be grateful if you could give it a try.

**Comment by EhrmannS** [comment]
Hi Jon, I just looked at it and ran a couple of tests. For `rescale(x, factor = 0.5, kernel = boxKernel())` it seems to work now. The new object will have the value of the upper left cell. Here I was wondering, if it would be possible to set some offset in `boxKernel()`? Maybe mean and/or range of the "box"-graph?

However, if I go for `rescale(x, factor = 2, kernel = boxKernel())`, then I still get the above described behaviour, where only the lower right of four cells will have the value of the previous object. Is up-scaling even a built-in feature?

**Comment by jonclayden** [comment]
Hi Steffen. Yes, upscaling should work. To take a simple example, the following is the behaviour I see based on the current tip of the master branch.

```{r}
library(mmand)
m <- matrix(c(1,1,1,0,1,1,0,0,1),3,3)
m
#      [,1] [,2] [,3]
# [1,]    1    0    0
# [2,]    1    1    0
# [3,]    1    1    1
rescale(m, 2, boxKernel())
#      [,1] [,2] [,3] [,4] [,5] [,6]
# [1,]    1    1    0    0    0    0
# [2,]    1    1    0    0    0    0
# [3,]    1    1    1    1    0    0
# [4,]    1    1    1    1    0    0
# [5,]    1    1    1    1    1    1
# [6,]    1    1    1    1    1    1
rescale(m, 0.5, boxKernel())
#      [,1] [,2]
# [1,]    1    0
# [2,]    1    1
```

This looks right to me. Do you get the same? If not, could you post your result and `sessionInfo()` please?

**Comment by EhrmannS** [comment]
All right, after restarting my R-Session your example (and also mine) now works. Thanks!
