### ISSUE TITLE
Literal Threshold problem

### ISSUE THREAD

**Issue by GhostValk** [jonclayden/mmand#5]
Hi!

When i apply a literal value for the threshold, nothing is rendered when using 'display' on the resulting image. The matrix values are correct, but no image is displayed, only the quartz window pops up blank (when using method='kmeans' it works properly)

Any idea of what could it be?

Thanks in advance!

**Comment by jonclayden** [comment]
Hi. Could you provide a simple self-contained example, please?

**Comment by GhostValk** [comment]
It's just what i said...

img<-readPng(some_image.png)

t1 <-threshold(img,method='kmeans')
t2 <-threshold(img,0.5) // Any value could be as the threshold level, also, i can put method='literal' or not, the result is the same..

display(t1) //  Shows the picture ok
display(t2) // Shows an empty canvas

Now if i print t2 to the console, the matrix is correct, it has the correct 1-0 values set, but the display function doesn't output anything.

I'm currently bypassing it by plotting it as a raster -> plot(as.raster(t2)) and it works.

**Comment by jonclayden** [comment]
OK, thanks. I wondered if it was specific to certain images. Could you try the new tip of the master branch, please, and see if it fixes the issue?
