### ISSUE TITLE
Is it possible to create kernels that are e.g. 3D rods?

### ISSUE THREAD

**Issue by mavavilj** [jonclayden/mmand#6]
Is it possible to create kernels that are e.g. 3D rods?

I.e. likely the equivalent of `SE = strel('line',len,deg)` here:

https://se.mathworks.com/help/images/ref/strel.html

**Comment by jonclayden** [comment]
Hi! Yes, such kernels should certainly be supported, but there is no specific helper function for creating them along the lines of the Matlab function you mention. You'd need two angles in 3D, but otherwise I assume it should be quite straightforward to do?

**Comment by jonclayden** [comment]
I'm assuming this is resolved.
